### PR TITLE
Gio example

### PR DESCRIPTION
**Pull request by bakkiaraj**
Added a Gnome Gio based example to demo the Linux desktop notification. Another version of notify.pl may be. Please pull it into main stream

### CODE REVIEW

**Comment by plicease** [comment]
I think you should consider making a module out of this instead of an example.  We have lots of examples now, but not many reverse dependencies on CPAN, and that is what we need more of them now.

Please make sure when making PRs to rebase your changes on top of the current master so that there aren't any merges or other extranious commits.

Please use the house style of the module when making PRs.  I understand it isn't quite what you are used to or like, but this is the style of this module, and it is pretty close to the main stream in Perl.

**Comment by bakkiaraj** [comment]
Ok. True. Its good to have modules depends on FFI::Platypus, Let me think
more.

On Fri, Mar 6, 2015 at 11:09 PM, Graham Ollis <notifications@github.com>
wrote:

> I think you should consider making a module out of this instead of an
> example. We have lots of examples now, but not many reverse dependencies on
> CPAN, and that is what we need more of them now.
>
> Please make sure when making PRs to rebase your changes on top of the
> current master so that there aren't any merges or other extranious commits.
>
> Please use the house style of the module when making PRs. I understand it
> isn't quite what you are used to or like, but this is the style of this
> module, and it is pretty close to the main stream in Perl.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plicease/FFI-Platypus/pull/48#issuecomment-77601055>.
>



-- 
Regards,
Bakkiaraj M

**Comment by bakkiaraj** [comment]
Ohh regarding the pull request, I thought this time, I made it right. I am
still getting GIT style :(

On Sat, Mar 7, 2015 at 1:49 PM, Bakkiaraj Murugesan <sam.bakki@gmail.com>
wrote:

> Ok. True. Its good to have modules depends on FFI::Platypus, Let me think
> more.
>
> On Fri, Mar 6, 2015 at 11:09 PM, Graham Ollis <notifications@github.com>
> wrote:
>
>> I think you should consider making a module out of this instead of an
>> example. We have lots of examples now, but not many reverse dependencies on
>> CPAN, and that is what we need more of them now.
>>
>> Please make sure when making PRs to rebase your changes on top of the
>> current master so that there aren't any merges or other extranious commits.
>>
>> Please use the house style of the module when making PRs. I understand it
>> isn't quite what you are used to or like, but this is the style of this
>> module, and it is pretty close to the main stream in Perl.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/plicease/FFI-Platypus/pull/48#issuecomment-77601055>.
>>
>
>
>
> --
> Regards,
> Bakkiaraj M
>



-- 
Regards,
Bakkiaraj M

**Comment by plicease** [comment]
Cool I look forward to seeing your module.

Regarding git, I think what you need to do is get rid of the commits in your master branch.  You can do that like this:

```
# make sure your master branch is checked out
% git checkout master
# add a remote to my repo, if you do not already have it
% git remote add plicease https://github.com/plicease/FFI-Platypus.git
# update all remote branches (-p prunes any local branches that no longer exists on the remote)
% git remote update -p
# reset your master branch to my master branch
% git reset --hard remotes/plicease/master
# push your new master branch up to github, using -f to force its replacement
% git push origin -f master
```

When you want to make a PR you  can create a new branch off of the current master

```
# first update your master
% git checkout master
% git pull plicease master
# create a newfeature banch from master
% git checkout -b newfeature master
% ... work work work ...
% git commit -a -m 'new feature'
% git push origin newfeature
```

git is powerful but its interface has a steep learning curve!  So I hope you don't feel discouraged.

**Comment by bakkiaraj** [comment]
Thanks Graham Ollis for the Git Way of Working. Day to Day I use SVN @Work
so Git feels little different but I appreciate its branching + merging
accuracy :).

On Sat, Mar 7, 2015 at 6:35 PM, Graham Ollis <notifications@github.com>
wrote:

> Cool I look forward to seeing your module.
>
> Regarding git, I think what you need to do is get rid of the commits in
> your master branch. You can do that like this:
>
> # make sure your master branch is checked out
> % git checkout master
> # add a remote to my repo, if you do not already have it
> % git remote add plicease https://github.com/plicease/FFI-Platypus.git
> # update all remote branches (-p prunes any local branches that no longer exists on the remote)
> % git remote update -p
> # reset your master branch to my master branch
> % git reset --hard remotes/plicease/master
> # push your new master branch up to github, using -f to force its replacement
> % git push origin -f master
>
> When you want to make a PR you can create a new branch off of the current
> master
>
> # first update your master
> % git checkout master
> % git pull plicease master
> # create a newfeature banch from master
> % git checkout -b newfeature master
> % ... work work work ...
> % git commit -a -m 'new feature'
> % git push origin newfeature
>
> git is powerful but its interface has a steep learning curve! So I hope
> you don't feel discouraged.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plicease/FFI-Platypus/pull/48#issuecomment-77688575>.
>



-- 
Regards,
Bakkiaraj M

**Comment by plicease** [comment]
@bakkiaraj SVN is great for work, but git is great for open source due to its distributed nature.  I'm closing this for now, let me know if/when you get this implemented as a module.

**Pull request closed without merging**
